name: CTFSimGUI
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - matplotlib=3.9.2
  - numpy=2.1.3
  - pyqt=5.15.10
  - pandas=2.2.3
